### ISSUE TITLE
XG does not compile with gcc7.1+matching glibc

### ISSUE THREAD

**Issue by JervenBolleman** [ekg/xg#68]
As reported in gitter
```
deps/xg/src/xg.cpp: In member function ‘int xg::XG::min_distance_in_paths(int64_t, bool, size_t, int64_t, bool, size_t) const’:
deps/xg/src/xg.cpp:2348:22: error: call of overloaded ‘abs(long unsigned int&)’ is ambiguous
             if (abs(o) < abs(min_dist)) {
```

**Comment by cartoonist** [comment]
I also came here to report this. :)

Actually the type of `o` is `size_t` (a.k.a `unsigned long int`) which is unsigned and `abs(o)` does not make any sense. There are two ways for workaround:

1. Remove `abs` function call and replace it by simply `o`.

```diff
diff --git a/src/xg.cpp b/src/xg.cpp
index de702bf..78a6a32 100644
--- a/src/xg.cpp
+++ b/src/xg.cpp
@@ -2450,7 +2450,7 @@ int XG::min_distance_in_paths(int64_t id1, bool is_rev1, size_t offset1,
     int min_dist = std::numeric_limits<int>::max();
     for (auto& c : dist) {
         for (auto& o : c.second) {
-            if (abs(o) < abs(min_dist)) {
+            if (o < abs(min_dist)) {
                 min_dist = o;
             }
         }
```

2. or cast `o` to type `std::intmax_t` which is the largest possible integer type:

```diff
diff --git a/src/xg.cpp b/src/xg.cpp
index de702bf..78a6a32 100644
--- a/src/xg.cpp
+++ b/src/xg.cpp
@@ -2450,7 +2450,7 @@ int XG::min_distance_in_paths(int64_t id1, bool is_rev1, size_t offset1,
     int min_dist = std::numeric_limits<int>::max();
     for (auto& c : dist) {
         for (auto& o : c.second) {
-            if (abs(o) < abs(min_dist)) {
+            if (abs(static_cast<std::intmax_t>(o)) < abs(min_dist)) {
                 min_dist = o;
             }
         }
```

The latter ensures that the expression is always non-negative even if the type of `o` would change to a signed type in future.

**Comment by glennhickey** [comment]
This has been fixed.  But please note that xg now lives in vg, so the
current version is here:

https://github.com/vgteam/vg/blob/master/src/xg.cpp

**Comment by cartoonist** [comment]
I didn't know that. Thanks for mentioning. How about 'libxg'?

**Comment by glennhickey** [comment]
Gone
